### ISSUE TITLE
Incompatibility with wsmtools

### ISSUE THREAD

**Issue by ronelm2000** [insanity54/encore-more#2]
Output Image from xtoast:
![image](https://user-images.githubusercontent.com/12634987/79302636-888ee000-7f1f-11ea-91d1-6b1ee211cd23.png)

Output Image from wsmtools:
![deck_date a live](https://user-images.githubusercontent.com/12634987/79302715-b70cbb00-7f1f-11ea-97c1-a4956dcbe260.jpg)

[wsmtools](https://github.com/ronelm2000/wsmtools) cards are arranged by serial due to its Deck Inspection APIs losing the ordinality of the input/output from encoredecks API. If possible, either:
- Expose a web API that outputs the following image from wsmtools.
   Proposed API: `https://xtoast.com/deck/WCiCTn736/sorted/serial`
- Rearrange the result image by lexicographical serial order (ascending).

**Comment by insanity54** [comment]
Thank you for this issue report. I think a predictable card order is a sensible default so I will implement this change on the `/deck/:deckId` endpoint.

**Comment by insanity54** [comment]
wontfix-- I'm shutting down xtoast
